# Generated by Django 3.2.9 on 2022-11-05 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=100)),
                ('route_est_time', models.TimeField()),
                ('route_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=100)),
                ('stop_lat', models.DecimalField(decimal_places=7, max_digits=9)),
                ('stop_lon', models.DecimalField(decimal_places=7, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_lat', models.DecimalField(decimal_places=7, max_digits=9)),
                ('passenger_lon', models.DecimalField(decimal_places=7, max_digits=9)),
                ('student_rank', models.IntegerField()),
                ('passenger_route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bustracker.route')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_lat', models.DecimalField(decimal_places=7, max_digits=9)),
                ('passenger_lon', models.DecimalField(decimal_places=7, max_digits=9)),
                ('driver_name', models.CharField(max_length=50)),
                ('passenger_route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bustracker.route')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_plate', models.CharField(max_length=10)),
                ('bus_lat', models.DecimalField(decimal_places=7, max_digits=9)),
                ('bus_long', models.DecimalField(decimal_places=7, max_digits=9)),
                ('bus_speed', models.DecimalField(decimal_places=6, max_digits=9)),
                ('bus_occupation', models.IntegerField()),
                ('bus_capacity', models.IntegerField()),
                ('bus_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bustracker.driver')),
                ('bus_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bustracker.route')),
            ],
        ),
    ]
