# Generated by Django 3.2.9 on 2022-11-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='passenger_rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
