# Generated by Django 3.2.9 on 2022-11-05 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bustracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='stop_status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.IntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bustracker.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bustracker.stop')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_time', models.TimeField()),
                ('reservation_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bustracker.bus')),
                ('reservation_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_end', to='bustracker.routestop')),
                ('reservation_passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bustracker.student')),
                ('reservation_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bustracker.routestop')),
            ],
        ),
    ]
